// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfCJJhKw-6d5vVl8mY8u7lQOPlMABjcs',
    appId: '1:8362647981:web:645728a4e3bb0315400124',
    messagingSenderId: '8362647981',
    projectId: 'naqdaapp',
    authDomain: 'naqdaapp.firebaseapp.com',
    storageBucket: 'naqdaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZeM5QLepzOlpEzySraa2gi2B9YMhEEM',
    appId: '1:8362647981:android:b96b4336fcdce018400124',
    messagingSenderId: '8362647981',
    projectId: 'naqdaapp',
    storageBucket: 'naqdaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLjq87xRxDjKWBN3kGmE1tTrBokXxY1I',
    appId: '1:8362647981:ios:1d2d027138e136aa400124',
    messagingSenderId: '8362647981',
    projectId: 'naqdaapp',
    storageBucket: 'naqdaapp.firebasestorage.app',
    iosBundleId: 'com.example.naqda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLjq87xRxDjKWBN3kGmE1tTrBokXxY1I',
    appId: '1:8362647981:ios:1d2d027138e136aa400124',
    messagingSenderId: '8362647981',
    projectId: 'naqdaapp',
    storageBucket: 'naqdaapp.firebasestorage.app',
    iosBundleId: 'com.example.naqda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfCJJhKw-6d5vVl8mY8u7lQOPlMABjcs',
    appId: '1:8362647981:web:2e861faea700640a400124',
    messagingSenderId: '8362647981',
    projectId: 'naqdaapp',
    authDomain: 'naqdaapp.firebaseapp.com',
    storageBucket: 'naqdaapp.firebasestorage.app',
  );
}
